sudo: required 
dist: xenial
language: c

before_install:
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo apt-get -y install python3 python3-pip lcov
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg-testing main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - if [[ ${COVERAGE} == 1 ]] ; then sudo /etc/init.d/postgresql stop ; fi
  - sudo pip install cpp-coveralls
  
before_script:
  - if [[ ${COVERAGE} != 1 ]] ; then createuser -U postgres -s travis ; fi

install: make && sudo make install

script:
  - if [[ ${COVERITY_SCAN_BRANCH} != 1 && ${COVERAGE} != 1 ]]; then make test ; fi
  - if [[ ${COVERAGE} == 1 ]] ; then ./run_coverage.sh ; fi

#after_success:
#  - if [[ ${COVERAGE} == 1 ]] ; then cpp-coveralls --exclude postgres.h --exclude pg_list.h --exclude stdio2.h --exclude dump.c --gcov-options '\-lp' ; fi

jobs:
  include:
#  - compiler: gcc
#    env:
#      - PGVERSION=12
#      - COVERAGE=1
# this is just a dummy PGVERSION (unused)
  - compiler: gcc
    env: PGVERSION=13
  - compiler: clang
    env: PGVERSION=13
  - compiler: gcc
    env: PGVERSION=12
  - compiler: clang
    env: PGVERSION=12
  - compiler: gcc
    env: PGVERSION=11
  - compiler: clang
    env: PGVERSION=11
  - compiler: gcc
    env: PGVERSION=10
  - compiler: clang
    env: PGVERSION=10
  - compiler: gcc
    env: PGVERSION=9.6
  - compiler: clang
    env: PGVERSION=9.6
  - compiler: gcc
    env: PGVERSION=9.5
  - compiler: clang
    env: PGVERSION=9.5

